# Generated by Django 2.2.9 on 2020-04-16 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0005_auto_20200416_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='group_title',
                                    to='posts.Group', verbose_name='Group'),
        ),
    ]
