# Generated by Django 2.2.9 on 2020-05-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0010_auto_20200427_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
