# Generated by Django 2.2.9 on 2020-06-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True,
                                       verbose_name='date published'),
        ),
    ]
